### ISSUE TITLE
WebDrivers loaded but crashing with AE

### ISSUE THREAD

**Issue by kobiohanna** [vulgo/webdriver.sh#11] opened 2018-04-20 01:15 UTC
I have a strange problem related to web drivers, system crashes every time I use web drivers in apps like AE, when using Apple drivers no problems.
I noticed that NVDAstartup by Apple is also loaded with Nvidia web drivers is that normal? can cause crashes?
![screen shot 2018-04-20 at 09 14 10](https://user-images.githubusercontent.com/20536487/39025683-3d85c64a-447b-11e8-810e-1762d9b3e67f.png)

**Comment by vulgo** [comment] 2018-04-20 14:08
I don't think the crashes are caused by NVDAStartup, it being loaded doesn't mean its doing anything after the drivers are started. If you are up to date with the latest drivers (and any supporting third-party kernel extensions) it could be an issue with the 387.10.10.10.30.106 web driver. Or CUDA if that is in use during crashes (and it wouldn't be with the Apple drivers...). Unless you are seeing errors during installation it doesn't sound like something that can be fixed in webdriver.sh

**Comment by kobiohanna** [comment] 2018-04-20 14:13
Thanks for your reply!!!!

Yes I suspect on the drivers as well, same machine build with 10.12.2 have
no problems...

**Closed** 2018-05-06 18:06 UTC
